### ISSUE TITLE
false values are not returned as strings like true values.

### ISSUE THREAD

**Issue by zigazajc007** [devcoder-xyz/php-dotenv#6]
Is there any parameter that I can use for false values to be returned as strings?

getenv function in PHP will return string or false if variable is undefined, but this library will also return false if variable is defined and set to false. So I can't know if variable has been defined or just set to false.

**Comment by vzool** [comment]
I think if you want to return all values as `string`, you can use the following:
```php
(new DevCoder\DotEnv(
    ROOT . '/.env',
    array(DevCoder\Processor\QuotedProcessor::class)
))->load();
```
